(define (problem viatgesProblemExt3_B)
    (:domain viatges)

    (:objects
        Barcelona Paris Roma Florencia Berlin Stuttgart - ciutat
        hotel_vela hotel_w hotel_eiffel hotel_louvre hotel_vatica hotel_coliseu hotel_art hotel_david hotel_mur hotel_brandenburg hotel_cervesa hotel_oktoberfest - hotel
    )

    (:init
        (= (minimCiutats) 4)
        (= (ciutatsVisitades) 0)
        (= (minDiesPerCiutat) 2)
        (= (maxDiesPerCiutat) 3)
        (= (minimDiesRuta) 10)
        (= (costTotal) 0)
        (= (pressupostMin) 50)
        (= (pressupostMax) 350)
        (= (diesEnRuta) 0)
        (= (diesEnCiutat Barcelona) 0)
        (= (diesEnCiutat Paris) 0)
        (= (diesEnCiutat Roma) 0)
        (= (diesEnCiutat Florencia) 0)
        (= (diesEnCiutat Berlin) 0)
        (= (diesEnCiutat Stuttgart) 0)

        (vol Paris Roma)
        (vol Roma Paris)
        (vol Paris Barcelona)
        (vol Barcelona Paris)
        (vol Paris Stuttgart)
        (vol Stuttgart Paris)
        (vol Barcelona Florencia)
        (vol Florencia Barcelona)
        (vol Barcelona Berlin)
        (vol Roma Barcelona)
        (vol Roma Berlin)
        (vol Berlin Roma)
        (vol Florencia Roma)
        (vol Florencia Berlin)
        (vol Berlin Stuttgart)
        (vol Stuttgart Berlin)

        (hotel_a hotel_vela Barcelona)
        (hotel_a hotel_w Barcelona)
        (hotel_a hotel_eiffel Paris)
        (hotel_a hotel_louvre Paris)
        (hotel_a hotel_vatica Roma)
        (hotel_a hotel_coliseu Roma)
        (hotel_a hotel_art Florencia)
        (hotel_a hotel_david Florencia)
        (hotel_a hotel_mur Berlin)
        (hotel_a hotel_brandenburg Berlin)
        (hotel_a hotel_cervesa Stuttgart)
        (hotel_a hotel_oktoberfest Stuttgart)

        (= (costVol Barcelona Paris) 20)
        (= (costVol Paris Barcelona) 20)
        (= (costVol Paris Roma) 25)
        (= (costVol Roma Paris) 25)
        (= (costVol Roma Berlin) 30)
        (= (costVol Berlin Roma) 30)
        (= (costVol Berlin Stuttgart) 12)
        (= (costVol Stuttgart Berlin) 12)
        (= (costVol Barcelona Florencia) 22)
        (= (costVol Florencia Barcelona) 22)
        (= (costVol Paris Stuttgart) 15)
        (= (costVol Barcelona Berlin) 28)
        (= (costVol Roma Barcelona) 24)
        (= (costVol Florencia Roma) 18)
        (= (costVol Florencia Berlin) 26)

        (= (costHotel hotel_vela) 25)
        (= (costHotel hotel_w) 18)
        (= (costHotel hotel_eiffel) 35)
        (= (costHotel hotel_louvre) 22)
        (= (costHotel hotel_vatica) 25)
        (= (costHotel hotel_coliseu) 15)
        (= (costHotel hotel_art) 22)
        (= (costHotel hotel_david) 16)
        (= (costHotel hotel_mur) 18)
        (= (costHotel hotel_brandenburg) 14)
        (= (costHotel hotel_cervesa) 15)
        (= (costHotel hotel_oktoberfest) 12)
    )

    (:goal (and
        (>= (ciutatsVisitades) (minimCiutats))
        (>= (diesEnRuta) (minimDiesRuta))
        (forall (?c - ciutat) (imply (usuari_a ?c) (>= (diesEnCiutat ?c) (minDiesPerCiutat))))
        (<= (costTotal) (pressupostMax))
        (>= (costTotal) (pressupostMin))
    ))

    (:metric minimize (costTotal))
)
