(define (problem viatgesProblemComplex)
    (:domain viatges)

    (:objects
        Barcelona Paris Roma Florencia Berlin Stuttgart London Madrid Amsterdam Viena - ciutat
        hotel_vela hotel_eiffel hotel_vatica hotel_art hotel_mur hotel_cervesa hotel_big_ben hotel_prado hotel_tulipa hotel_opera - hotel
    )

    (:init
        (= (minimCiutats) 6)
        (= (ciutatsVisitades) 0)
        (= (minDiesPerCiutat) 2)
        (= (maxDiesPerCiutat) 4)
        (= (minimDiesRuta) 16)
        (= (diesEnRuta) 0)
        (= (diesEnCiutat Barcelona) 0)
        (= (diesEnCiutat Paris) 0)
        (= (diesEnCiutat Roma) 0)
        (= (diesEnCiutat Florencia) 0)
        (= (diesEnCiutat Berlin) 0)
        (= (diesEnCiutat Stuttgart) 0)
        (= (diesEnCiutat London) 0)
        (= (diesEnCiutat Madrid) 0)
        (= (diesEnCiutat Amsterdam) 0)
        (= (diesEnCiutat Viena) 0)
        (hotel_a hotel_prado Madrid)
        (hotel_a hotel_vela Barcelona)
        (hotel_a hotel_eiffel Paris)
        (hotel_a hotel_big_ben London)
        (hotel_a hotel_tulipa Amsterdam)
        (hotel_a hotel_cervesa Stuttgart)
        (hotel_a hotel_mur Berlin)
        (hotel_a hotel_art Florencia)
        (hotel_a hotel_vatica Roma)
        (hotel_a hotel_opera Viena)
        (vol Madrid Barcelona)
        (vol Madrid Paris)
        (vol Barcelona Madrid)
        (vol Barcelona Florencia)
        (vol Barcelona Roma)
        (vol Paris London)
        (vol Paris Stuttgart)
        (vol Paris Amsterdam)
        (vol London Amsterdam)
        (vol London Paris)
        (vol Amsterdam Berlin)
        (vol Amsterdam London)
        (vol Stuttgart Berlin)
        (vol Stuttgart Viena)
        (vol Berlin Viena)
        (vol Berlin Roma)
        (vol Florencia Roma)
        (vol Florencia Barcelona)
        (vol Roma Florencia)
        (vol Roma Viena)
        (vol Viena Berlin)
        (vol Viena Roma)
    )

    (:goal (and
        (>= (ciutatsVisitades) (minimCiutats))
        (>= (diesEnRuta) (minimDiesRuta))
        (forall (?c - ciutat) (imply (usuari_a ?c) (>= (diesEnCiutat ?c) (minDiesPerCiutat))))
        ;; l'ultima ciutat tambe ha de tenir el minim de dies
    ))
)
