(define (problem viatgesProblemInteresInvertit)
    (:domain viatges)

    (:objects Barcelona Paris Roma Florencia Berlin Stuttgart - ciutat
              hotel_vela hotel_eiffel hotel_vatica hotel_art hotel_mur hotel_cervesa - hotel
    )

    (:init
        (= (minimCiutats) 3)
        (= (minDiesPerCiutat) 2)
        (= (maxDiesPerCiutat) 4)
        (= (minimDiesRuta) 6)
        (= (interesTotal) 0)
        (= (ciutatsVisitades) 0)
        (= (diesEnRuta) 0)
        (= (diesEnCiutat Barcelona) 0)
        (= (diesEnCiutat Paris) 0)
        (= (diesEnCiutat Roma) 0)
        (= (diesEnCiutat Florencia) 0)
        (= (diesEnCiutat Berlin) 0)
        (= (diesEnCiutat Stuttgart) 0)
        (= (interes Roma) 1)
        (= (interes Berlin) 1)
        (= (interes Florencia) 2)
        (= (interes Stuttgart) 2)
        (= (interes Barcelona) 3)
        (= (interes Paris) 3)

        (vol Paris Roma)
        (vol Paris Stuttgart)
        (vol Paris Barcelona)
        (vol Barcelona Paris)
        (vol Barcelona Florencia)
        (vol Roma Barcelona)
        (vol Roma Berlin)
        (vol Florencia Roma)
        (vol Florencia Barcelona)
        (vol Florencia Berlin)
        (vol Berlin Roma)
        (vol Berlin Stuttgart)
        (vol Stuttgart Florencia)
        (vol Stuttgart Berlin)
        (hotel_a hotel_vela Barcelona)
        (hotel_a hotel_eiffel Paris)
        (hotel_a hotel_cervesa Stuttgart)
        (hotel_a hotel_mur Berlin)
        (hotel_a hotel_vatica Roma)
        (hotel_a hotel_art Florencia)
    )

    (:goal (and (>= (ciutatsVisitades) (minimCiutats))
                    (>= (diesEnRuta) (minimDiesRuta))))

    (:metric minimize (interesTotal))
)
