all:numeros listaParametros suma

numeros: numeros.c mis_funciones.c
	gcc -o numeros numeros.c mis_funciones.c

listaParametros: listaParametros.c mis_funciones.c
	gcc -o listaParametros listaParametros.c mis_funciones.c

suma: suma.c mis_funciones.c
	gcc -o suma suma.c mis_funciones.c
clean:
	rm numeros
